# Generated by Django 4.2.6 on 2023-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Event Name")),
                (
                    "event_documents",
                    models.FileField(blank=True, null=True, upload_to="files/"),
                ),
            ],
        ),
    ]
