# Generated by Django 4.2.6 on 2023-11-22 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
