# Generated by Django 4.2.6 on 2023-12-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EventId", models.CharField(max_length=200)),
                ("UserName", models.CharField(max_length=50)),
                ("TimeStamp", models.DateTimeField(auto_now_add=True)),
                ("PostId", models.IntegerField()),
                ("Message", models.TextField(max_length=500)),
            ],
        ),
    ]
